'use strict';
/* ════════════════════════════════════════════════
   IB Prep · data_knowledge_2.js
   New decks: M&A Process | ECM & ABB | DCM & Financing |
              PE & Buy-and-Build | Case Studies | Analyst Toolkit
════════════════════════════════════════════════ */

const KNOWLEDGE_2 = [

  /* ══════════════════════════════════════════════
     DECK: M&A PROCESS (ma_process)
  ══════════════════════════════════════════════ */

  // --- Sell-Side M&A Phases ---
  { deckId:'ma_process', q:'Sell-Side M&A: Hvad sker i Pitching-fasen (Uge 0–2)?',
    a:`Alt starter med pitchet. Klienten (CEO, CFO eller PE-fonds managing partner) indikerer at de overvejer et salg.<br><br><strong>Analytiker-leverancer:</strong><ul><li>Pitch book (30–60 sider): markedsanalyse, peer-værdiansættelse, potentielle købere</li><li>Comps-tabeller og precedent transactions</li><li>Preliminary valuation range</li><li>Forslag til procesdesign og timing</li></ul><strong>Husk:</strong> Pitch book skal være <em>fejlfrit</em> — én formatfejl signalerer manglende disciplin.` },

  { deckId:'ma_process', q:'Sell-Side M&A: Mandatvinding & Engagement Letter (Uge 2–4) — Hvad aftales?',
    a:`Når mandatet er vundet, underskrives et <strong>engagement letter</strong>:<br><br><ul><li><strong>Scope:</strong> Hvad banken leverer (sell-side advisory, fairness opinion, etc.)</li><li><strong>Fee-struktur:</strong> Retainer + success fee baseret på transaktionsværdi</li><li><strong>Eksklusivitetsperiode:</strong> Typisk 6–12 måneder</li></ul><strong>Typiske fees:</strong><br>• Mid-market (EV EUR 100–500 mio.): <strong>1–3% af EV</strong><br>• Større transaktioner: <strong>0,5–1% af EV</strong>` },

  { deckId:'ma_process', q:'Sell-Side M&A: Teaser & NDA-fasen (Uge 4–6) — Hvad er en teaser?',
    a:`Et <strong>anonymiseret 2-siders dokument</strong> distribueret til en long list af potentielle købere (50–100 navne).<br><br><strong>Indhold:</strong> Overordnet virksomhedsbeskrivelse uden at afsløre identitet. Sektor, størrelse, vækstprofil.<br><br><strong>Proces:</strong><ol><li>Teaser sendes til long list</li><li>Interesserede parter underskriver <strong>NDA</strong></li><li>Først derefter modtages yderligere information</li></ol><strong>Analyst-opgave:</strong> Bygge og vedligeholde buyer-listen i Excel med kontaktinfo, sektorrelevans, finansiel kapacitet og status-tracking.` },

  { deckId:'ma_process', q:'Sell-Side M&A: Information Memorandum (Uge 6–12) — Hvad indeholder det?',
    a:`IM'en er det <strong>centrale salgsdokument</strong> — typisk 80–150 sider:<br><br><ul><li>Virksomhedsbeskrivelse og markedsposition</li><li>Finansiel historik og fremskrivninger (3–5 år)</li><li>Ledelsespræsentation</li><li>Investeringshighlights</li></ul><strong>Analyst bygger:</strong> Alle finansielle tabeller, grafer og den underliggende model (management case, base case, downside case).<br><br><strong>Suppleres af:</strong> Fact Book (kompileret med revisionshus via Financial Due Diligence/FDD).` },

  { deckId:'ma_process', q:'Sell-Side M&A: Indikative Bud / NBO (Non-Binding Offers) — Hvad evalueres?',
    a:`Interesserede købere indsender <strong>Non-Binding Offers (NBOs)</strong> efter at have læst IM.<br><br><strong>Analyst bygger "bid comparison"-matrixer:</strong><ul><li>Budstørrelse (Enterprise Value)</li><li>Underliggende antagelser (EBITDA-multipel, synergier)</li><li>Krav til due diligence</li><li>Dokumenteret finansieringssikkerhed</li></ul><strong>Output:</strong> Ledelsen og rådgiver udvælger et snævert felt af bydere (Shortlist, typisk 4–8 parter) til anden runde.` },

  { deckId:'ma_process', q:'Sell-Side M&A: Datarum (VDR) & Management Presentations (Uge 12–22)',
    a:`<strong>Virtual Data Room (VDR)</strong> — typisk Datasite, Intralinks eller Firmex:<br><ul><li>Hundredvis til tusindvis af dokumenter</li><li>Organiseret i standardstruktur: financial, legal, tax, commercial, HR, IT, ESG, insurance, IP, regulatory</li></ul><strong>Q&A-management:</strong> Daglig opgave. Response-tid typisk 48 timer. Forsinkelser sænker købers tillid.<br><br><strong>Management Presentations:</strong> Virksomhedens ledelse præsenterer for short-listede købere. Bankens rolle: coache ledelsen, strukturere præsentation, forberede back-up-slides.` },

  { deckId:'ma_process', q:'Sell-Side M&A: SPA-forhandling & Binding Bids (Uge 20–26)',
    a:`Finale bud afgives med markup af <strong>Sale and Purchase Agreement (SPA)</strong>.<br><br><strong>Forhandlingspunkter:</strong><ul><li>Pris og EV-to-equity bridge</li><li>Warranty & Indemnity-pakke</li><li>Earn-out-mekanismer</li><li><strong>Locked Box</strong> vs. <strong>Completion Accounts</strong></li><li>Closing conditions</li></ul><strong>Analyst-opgave:</strong> Løbende opdatering af merger model, scenarieanalyse af earn-outs, bridge-tabeller der reconciler EV til equity value.<br><br><strong>Signing → Closing:</strong> Typisk 4–8 uger (regulatory approvals, competition clearance).` },

  { deckId:'ma_process', q:'Locked Box vs. Completion Accounts — Hvad er forskellen?',
    a:`To mekanismer til at fastsætte den endelige købspris:<br><br><strong>Locked Box:</strong><ul><li>Prisen låses på en <em>historisk balance-dato</em> ("locked box date")</li><li>Ingen prisregulering efter signing</li><li>"Leakage"-beskyttelse: sælger må ikke trække penge ud efter lock-dato</li><li>Foretrukket af PE-sælgere (prisvished)</li></ul><strong>Completion Accounts:</strong><ul><li>Prisen justeres baseret på <em>aktuel</em> balance på closing-datoen</li><li>Kræver post-closing opgørelse og potentiel tvist</li><li>Mere usikkerhed, men afspejler realiteten</li></ul><strong>Trend:</strong> Locked Box dominerer i europæiske M&A (~70%+ af handler).` },

  { deckId:'ma_process', q:'EV-to-Equity Bridge i M&A — Hvordan beregnes den endelige pris?',
    a:`<strong>Enterprise Value (EV)</strong> er hvad hele virksomheden er værd.<br><strong>Equity Value</strong> er hvad sælger faktisk modtager.<br><br><strong>Broen:</strong><br>EV<br>− Nettogæld (Net Debt)<br>− Pensionsforpligtelser<br>− Minoritetsinteresser<br>± Working capital-justering (vs. NWC peg)<br>± Andre gældslignende poster<br>= <strong>Equity Value (Købesum)</strong><br><br><strong>Kritisk for analytiker:</strong> Definitionen af "Net Debt" og "NWC peg" er de mest forhandlede punkter i en SPA. Selv små ændringer kan betyde millioner.` },

  { deckId:'ma_process', q:'Hvad er et Process Letter, og hvad indeholder det?',
    a:`Et <strong>Process Letter</strong> er det formelle brev der sendes til short-listede købere og specificerer:<br><br><ul><li>Tidsplan for processen</li><li>Deadlines for bud (NBO og Binding Bid)</li><li>Format for budafgivelse</li><li>Krav til finansieringsdokumentation</li><li>Regler for datarumsadgang</li><li>Kontaktoplysninger og informationsrestriktioner</li></ul><strong>Formål:</strong> Sikre en fair, struktureret auktion med lige vilkår for alle bydere. Giver sælger kontrol over timing og proces.` },

  { deckId:'ma_process', q:'Buy-Side M&A: Hvordan adskiller processen sig fra sell-side?',
    a:`<strong>Buy-side</strong> er rådgivning til den <em>købende</em> part:<br><br><strong>Nøgleopgaver:</strong><ul><li>Target-screening og identificering</li><li>Standalone-værdiansættelse + synergiberegning</li><li>Due diligence-koordinering (financial, commercial, legal, tax)</li><li>Forhandlingsrådgivning om pris og vilkår</li><li>Finansieringsstrukturering (koordinering med DCM)</li></ul><strong>Forskel fra sell-side:</strong><br>• Ingen IM/teaser — i stedet bygges intern investeringssags-memo<br>• Fokus på synergier og integration (ikke equity story)<br>• Kortere, mere fokuseret proces<br>• Fee ofte lavere (0,5–1,5% af EV)` },

  { deckId:'ma_process', q:'Vendor Due Diligence (VDD) — Hvad er det og hvem bestiller den?',
    a:`<strong>Sælgers rådgiver</strong> bestiller VDD-rapporter via BIG4 (Deloitte, EY, PwC, KPMG) <em>før</em> processen starter:<br><br><strong>Typer:</strong><ul><li>Financial VDD (historisk EBITDA, NWC, capex, net debt)</li><li>Commercial VDD (marked, konkurrence, vækstdrivere)</li><li>Tax VDD (skattestruktur, risici)</li><li>Legal VDD (kontrakter, tvister, IP)</li><li>ESG VDD (bæredygtighedsrisici)</li></ul><strong>Fordel:</strong> Accelererer processen (købere læser VDD fra dag 1).<br><strong>Konflikt:</strong> BIG4 betales af sælger og har incitament til at sætte selskabet i bedst muligt lys.` },

  { deckId:'ma_process', q:'Long List → Short List → Preferred Bidder: Hvad er udvælgelseskriterierne?',
    a:`<strong>Long List (50–100 navne):</strong><ul><li>Alle tænkelige købere: strategiske, PE-fonde, infrastruktur-fonde</li><li>Filtreret på sektor, geografi, størrelse, track record</li></ul><strong>Short List (15–25 navne):</strong><ul><li>Har underskrevet NDA og vist reel interesse</li><li>Har dokumenteret finansieringskapacitet</li><li>Strategisk fit og historik med lignende transaktioner</li></ul><strong>Preferred Bidder (1–2):</strong><ul><li>Højeste indikative bud</li><li>Stærkest finansieringsbevis (commitment letter)</li><li>Lavest regulatorisk risiko</li><li>Bedst certainty of close</li></ul>` },

  // --- Terminologi ---
  { deckId:'ma_process', q:'Hvad er en "Carve-Out", og hvorfor er det komplekst?',
    a:`En <strong>carve-out</strong> er salg af en division/afdeling fra en større virksomhed:<br><br><strong>Kompleksitet:</strong><ul><li>Separation af shared services (IT, HR, finans)</li><li>Oprettelse af standalone financials (ofte ikke historisk tilgængelige)</li><li>TSA (Transitional Service Agreements) — sælger leverer fortsat services i overgangsperiode</li><li>Medarbejder- og kontrakttildeling</li><li>Transfer pricing-justeringer</li></ul><strong>Eksempel:</strong> Fortum solgte sin Recycling & Waste-division til Summa Equity (EUR 800 mio., 2024) med Danske Bank som Financial Adviser.` },

  { deckId:'ma_process', q:'Hvad er "Deal Momentum", og hvorfor er det afgørende?',
    a:`<strong>Deal Momentum</strong> er den fremdrift og energi der holder en transaktion på sporet:<br><br><strong>Hvad skaber momentum:</strong><ul><li>Hurtig respons på Q&A i datarum</li><li>Velorganiserede management presentations</li><li>Proaktiv kommunikation med bydere</li><li>Klar proceskalender med deadlines</li></ul><strong>Hvad dræber momentum:</strong><ul><li>Forsinkelser i datarummet (>48 timer)</li><li>Modstridende signaler fra sælger</li><li>Uorganiserede dokumenter</li><li>Ændringer i management case midt i processen</li></ul><em>"When a deal loses momentum, it often never recovers."</em>` },


  /* ══════════════════════════════════════════════
     DECK: ECM & ABB (ecm_abb)
  ══════════════════════════════════════════════ */

  { deckId:'ecm_abb', q:'ABB (Accelerated Bookbuild): Hvad er den præcise overnight-tidslinje?',
    a:`<strong>T+0:</strong><br><table style="width:100%;font-size:13px"><tr><td><strong>16:00–17:00</strong></td><td>Pre-sounding / Wall-Crossing: Kerneinvestorer gøres til insidere</td></tr><tr><td><strong>17:00</strong></td><td>Markedet lukker</td></tr><tr><td><strong>17:15–17:30</strong></td><td>Launch Announcement via selskabsmeddelelse</td></tr><tr><td><strong>17:30–22:00</strong></td><td>Bookbuilding: Equity Sales distribuerer globalt, ordrer indsamles</td></tr><tr><td><strong>22:00–00:00</strong></td><td>Pricing & bogen lukkes. Typisk 5–10% rabat på lukkekurs</td></tr><tr><td><strong>00:00–06:00</strong></td><td>Allokering: Strategisk fordeling til long-only > hedgefonde</td></tr></table><strong>T+1, 08:00:</strong> Pricing Announcement før børsåbning<br><strong>T+3:</strong> Settlement` },

  { deckId:'ecm_abb', q:'ABB: Hvad er "Wall-Crossing" og hvorfor er det regulatorisk følsomt?',
    a:`<strong>Wall-Crossing</strong> = at gøre udvalgte investorer til insidere <em>før</em> transaktionen annonceres:<br><br><ul><li>Investorer modtager MNPI (Material Non-Public Information)</li><li>De underlægges <strong>handelsforbud</strong></li><li>Formålet er at afdække priselasticitet og baseline-efterspørgsel</li></ul><strong>Regulatorisk:</strong><ul><li>Kun tilladt med investorens samtykke</li><li>Skal dokumenteres grundigt (MAR compliance)</li><li>Risiko: Hvis investoren handler inden annoncering = insider trading</li></ul><strong>Typisk:</strong> 5–10 kerneinvestorer wall-crosses.` },

  { deckId:'ecm_abb', q:'ABB: Hvad er en "Shadow Book" og hvem vedligeholder den?',
    a:`<strong>Shadow Book</strong> er ECM-analytikerens realtidsoversigt over ordrebogen under bookbuilding:<br><br><strong>Indeholder:</strong><ul><li>Alle indkomne ordrer (investor, volumen, prislimit)</li><li>Kumulativ dækning vs. target</li><li>Oversubscription-ratio (mål: 1,5x–3x+)</li><li>Kvalitetsvurdering af investorer (long-only vs. fast money)</li></ul><strong>Kritisk:</strong> Kommafejl i allokeringsregnearket kan betyde fejlallokeringer for millioner.<br><br><strong>Analytikeren monitorerer:</strong><br>• Hvornår bogen er "covered" (fuldt tegnet)<br>• Hvornår den er "oversubscribed"` },

  { deckId:'ecm_abb', q:'Main Market vs. First North: Hvad er de vigtigste forskelle?',
    a:`<table style="width:100%;font-size:12px"><tr><th></th><th>Main Market</th><th>First North</th></tr><tr><td><strong>Status</strong></td><td>Reguleret marked (MiFID II)</td><td>MTF / SME Growth Market</td></tr><tr><td><strong>Tilsyn</strong></td><td>Finanstilsynet + Nasdaq</td><td>Nasdaq (+ Certified Adviser)</td></tr><tr><td><strong>Prospekt</strong></td><td>Fuldt EU-prospekt</td><td>Selskabsbeskrivelse</td></tr><tr><td><strong>Historik</strong></td><td>3 år revideret</td><td>Ingen minimumskrav</td></tr><tr><td><strong>Free float</strong></td><td>Min. 25%</td><td>Min. 10%</td></tr><tr><td><strong>Regnskab</strong></td><td>IFRS obligatorisk</td><td>Dansk GAAP ok</td></tr><tr><td><strong>Governance</strong></td><td>Følg-eller-forklar</td><td>Ikke påkrævet</td></tr></table><br><strong>First North Premier:</strong> Mellemtrin med strengere krav — stepping stone til Main Market.` },

  { deckId:'ecm_abb', q:'IPO-Readiness: Hvad kræves i 2026 ud over det finansielle?',
    a:`IPO-readiness har tre dimensioner:<br><br><strong>1. Finansiel:</strong><ul><li>Robust forecasting med identificerede nøgleantagelser</li><li>3 år revideret under IFRS (Main Market)</li><li>Kvartalsvis guidance-kapabilitet</li></ul><strong>2. Organisatorisk:</strong><ul><li>Optimal holdingstruktur</li><li>Bestyrelse + revisionskomité ifm. Corporate Governance</li><li>IR-team on-boarded <strong>min. 12 mdr.</strong> før notering</li><li>"Equity story-ready" CEO og CFO</li></ul><strong>3. ESG & Compliance:</strong><ul><li>97% af dealmakers integrerer ESG i M&A-strategier</li><li>CSRD-krav: Scope 1/2/3, diversitets-KPI'er</li><li>Data Governance som selvstændig DD-dimension</li></ul>` },

  { deckId:'ecm_abb', q:'IPO-processen: Hvad er Equity Story og hvorfor er den afgørende?',
    a:`<strong>Equity Story</strong> = den narrative ramme der oversætter virksomhedens strategi til en investeringscase for børsnoterede investorer:<br><br><strong>Skal indeholde:</strong><ul><li>Klare KPI'er med målbare targets</li><li>Veldefineret væksthistorie (organisk + M&A)</li><li>Peer-positionering (hvorfor handler vi til X multipel?)</li><li>Transparent ESG-rapportering</li><li>Management track record</li></ul><strong>Output:</strong><ul><li>Prospektudkast (200–350 sider)</li><li>Investor-præsentation</li><li>Roadshow-materiale</li></ul>Koordineres med Finanstilsynet: 4–5 udkast over 2–3 måneder.` },

  { deckId:'ecm_abb', q:'IPO: Lock-up perioder og PE sell-down — Hvad er mekanismen?',
    a:`<strong>Lock-up:</strong> Sælgende aktionærer accepterer ikke at sælge aktier i en periode efter notering/ABB:<br><br><ul><li>IPO: Typisk <strong>180–360 dage</strong></li><li>ABB: Typisk <strong>30–180 dage</strong></li></ul><strong>PE Sell-Down:</strong><ol><li>PE-fond tager virksomheden på børsen via IPO (sælger typisk 25–40%)</li><li>Lock-up periode udløber (180 dage)</li><li>ABB #1: PE sælger yderligere 10–20%</li><li>ABB #2: PE sælger resterende aktier</li><li>Full exit opnået over 12–24 måneder</li></ol>ABB er standardværktøjet til PE sell-down i allerede noterede selskaber.` },

  { deckId:'ecm_abb', q:'Dansk IPO-pipeline 2025–2026: Hvem forbereder sig?',
    a:`Det danske IPO-marked har været <strong>de facto inaktivt siden 2022</strong>. Nul kroner rejst i 2023 og 2024.<br><br><strong>Pipeline:</strong><ul><li><strong>Leo Pharma</strong> — sigter mod notering i 2026</li><li><strong>WS Audiology</strong> — forbereder potentiel IPO</li><li><strong>Nordic Bioscience</strong> — forberedt men forventet udskudt</li><li><strong>Pleo</strong> — planlægger notering i udlandet (ikke Nasdaq CPH)</li><li><strong>Visma</strong> — IPO London H1 2026 (Danske Bank som bookrunner)</li></ul><strong>53 overdue PE-exits</strong> i Danmark = massiv pipeline af potentielle IPO- eller M&A-exits.` },

  { deckId:'ecm_abb', q:'Hvad er en Rights Issue (Fortegningsemission) vs. Rettet Emission?',
    a:`<strong>Rights Issue (Fortegningsemission):</strong><ul><li>Eksisterende aktionærer tilbydes nye aktier pro rata</li><li>Tegningsretter kan handles separat</li><li>Typisk 2–4 ugers tegningsperiode</li><li>Fuld regulatorisk behandling (prospekt)</li><li>Ofte ved rekapitalisering (f.eks. SAS)</li></ul><strong>Rettet Emission (Private Placement):</strong><ul><li>Nye aktier sælges direkte til udvalgte investorer</li><li>Ingen fortegningsret for eksisterende aktionærer</li><li>Meget hurtigere (kan udføres som ABB overnight)</li><li>Dilution for ikke-deltagende aktionærer</li></ul>` },


  /* ══════════════════════════════════════════════
     DECK: DCM & FINANCING (dcm_financing)
  ══════════════════════════════════════════════ */

  { deckId:'dcm_financing', q:'LBO Kapitalstruktur: Hvad er de typiske lag i en nordisk buyout?',
    a:`<strong>Typisk nordisk LBO-kapitalstruktur:</strong><br><br><table style="width:100%;font-size:12px"><tr><td><strong>Senior Debt (Bank)</strong></td><td>50–60% af total</td><td>Marginal: ~375 bps (Q4 2025)</td></tr><tr><td><strong>Unitranche</strong></td><td>Alternativ til senior+mezz</td><td>Marginal: ~450–521 bps</td></tr><tr><td><strong>Nordic HY</strong></td><td>Supplement</td><td>Kupon: 7–8%</td></tr><tr><td><strong>Direct Lending</strong></td><td>Stigende</td><td>~521 bps (Q4 2025)</td></tr><tr><td><strong>Equity</strong></td><td>30–50%</td><td>Markant højere end pre-GFC</td></tr></table><br><strong>Typisk leverage:</strong> Senior 4,3x Net Debt/EBITDA, total 4,7–4,9x.` },

  { deckId:'dcm_financing', q:'Stapled Financing: Hvad er det og hvorfor bruges det?',
    a:`<strong>Stapled Financing</strong> = forhåndsarrangeret gældspakke tilbudt af sælgers rådgiverbank til alle bydere:<br><br><strong>Tre formål:</strong><ol><li><strong>Udvide buyer-poolen:</strong> Også mindre købere kan opnå leverage</li><li><strong>Accelerere tidslinjer:</strong> Eliminerer forsinkelser fra separat finansieringsarrangement</li><li><strong>Maksimere prisen:</strong> Fjerner finansieringsusikkerhed</li></ol><strong>~30% af M&A-handler</strong> i 2024 anvendte stapled financing.<br><br><strong>Interessekonflikt:</strong> Banken er samtidig sælgers rådgiver OG potentiel långiver til køber. Kræver intern governance.` },

  { deckId:'dcm_financing', q:'Unitranche vs. Senior + Mezzanine — Hvad er forskellen?',
    a:`<strong>Unitranche:</strong><ul><li>Ét enkelt gældsinstrument der kombinerer senior og mezzanine</li><li>Én långiver, én dokumentation, én rente</li><li>Hurtigere eksekvering og enklere struktur</li><li>Populær i Norden for mid-market LBOs</li></ul><strong>Senior + Mezzanine (traditionelt):</strong><ul><li>To separate instrumenter med forskellige prioriteter</li><li>Senior = lavere rente, højere prioritet</li><li>Mezzanine = højere rente (12–15%), lavere prioritet</li><li>Mere fleksibelt men mere komplekst</li></ul><strong>Eksempel:</strong> Adevinta gennemførte EUR 6,5 mia. unitranche-refinansiering i 2025 — den største europæiske direct lending-transaktion nogensinde.` },

  { deckId:'dcm_financing', q:'DCM-koordinering i en M&A-proces: Hvad er de 4 faser?',
    a:`<strong>Fase 1 — Debt Capacity-analyse</strong> (parallelt med IM):<br>DCM analyserer cash flows, EBITDA-stabilitet, NWC, capex → indikativt financing term sheet.<br><br><strong>Fase 2 — Lender Engagement</strong> (parallelt med Phase 1):<br>Engagerer nordiske banker (Nordea, SEB, DNB, Danske), direct lending-fonde, HY-markedet.<br><br><strong>Fase 3 — Commitment Letters</strong> (før final bids):<br>Juridisk bindende forpligtelser fra långivere. Inkluderes i PE-fondenes bud.<br><br><strong>Fase 4 — Financing Documentation</strong> (parallelt med SPA):<br>Detaljerede facilitetsaftaler. Closing af M&A og financing sker simultant.` },

  { deckId:'dcm_financing', q:'Hvordan påvirker DCM-pakken budniveauet i en M&A-auktion?',
    a:`<strong>Nøgleindsigt:</strong> Desto mere gæld en køber kan rejse på attraktive vilkår, desto højere kan de byde.<br><br><strong>Matematikken:</strong><br>• PE-fond kræver f.eks. 20% IRR<br>• Equity check er fast (30–50% af EV)<br>• Hvis DCM giver 5,0x leverage i stedet for 4,0x:<br>→ Køber kan byde højere EV med samme equity check<br>→ IRR-kravet opfyldes stadig pga. mere gæld<br><br><strong>Resultat:</strong> En stærk DCM-pakke med højere leverage eller lempeligere covenants presser værdiansættelsesmultiplerne op for sælger.<br><br><em>"Financing drives valuation"</em> — dette er symbiotisk M&A/DCM-strukturering.` },

  { deckId:'dcm_financing', q:'Det nordiske High Yield-marked: Nøgletal og karakteristika',
    a:`<strong>Størrelse:</strong> ~EUR 55 mia. outstanding, ~1/5 af det europæiske HY-marked.<br><br><strong>2024 rekord:</strong> NOK 240 mia. (~EUR 20,4 mia.) i new issue — +72% YoY.<br><br><strong>Karakteristika:</strong><ul><li>~35% af markedet er PE-ejede virksomheder</li><li>Typiske kuponer: 7–8% (primo 2025)</li><li>Norsk lov dominerer (svensk/dansk lov stigende)</li><li>Pareto Securities er markedsleder</li><li>DNB, Nordea, SEB, Danske Bank er aktive arrangører</li></ul><strong>Anvendelse:</strong> Opkøbsfinansiering, refinansiering, buy-and-build expansion.` },

  { deckId:'dcm_financing', q:'Covenants i LBO-gæld: Maintenance vs. Incurrence — Hvad er forskellen?',
    a:`<strong>Maintenance Covenants:</strong><ul><li>Testes <em>løbende</em> (typisk kvartalsvist)</li><li>Eksempel: Net Debt/EBITDA må ikke overstige 5,0x ved kvartalsluk</li><li>Bruges i traditionelle banklån</li><li>Proaktiv beskyttelse for långiver</li></ul><strong>Incurrence Covenants:</strong><ul><li>Testes kun ved <em>specifikke handlinger</em> (optag af ny gæld, udbetaling af udbytte)</li><li>Langt mere låntager-venlige</li><li>Standard i HY-obligationer og unitranches</li></ul><strong>Trend:</strong> "Covenant-lite" (cov-lite) strukturer dominerer i dag — længere reb til låntagere, men højere risiko for långivere.` },

  { deckId:'dcm_financing', q:'Revolving Credit Facility (RCF): Hvad er det og hvad bruges det til?',
    a:`<strong>RCF</strong> er en fleksibel kreditfacilitet der kan trækkes og tilbagebetales løbende:<br><br><strong>I en LBO:</strong><ul><li>Bruges til working capital-behov og kortsigtede likviditetsudsving</li><li>Typisk størrelse: 10–15% af total gæld</li><li>Lavere marginal end term loan (da den sjældent er fuldt trukket)</li><li>Commitment fee på utrukket del (~30–50% af marginal)</li></ul><strong>Vigtig distinktion:</strong> RCF'en er <em>ikke</em> en del af den permanente finansiering — den er et likviditetsnet. I LBO-modellen holdes den typisk utrukket i base case.` },

  { deckId:'dcm_financing', q:'Hvad er en Dividend Recapitalization, og hvorfor er det kontroversielt?',
    a:`<strong>Dividend Recap</strong> = PE-fond optager ny gæld i porteføljevirksomheden for at betale udbytte til sig selv:<br><br><strong>Mekanik:</strong><ol><li>Virksomheden optager ny gæld (typisk HY eller unitranche)</li><li>Provenuet betales som udbytte til PE-fonden</li><li>PE-fonden reducerer sin equity-eksponering</li></ol><strong>Kontroversielt fordi:</strong><ul><li>Øger virksomhedens leverage markant</li><li>Penge forlader virksomheden (modsat geninervstering)</li><li>Gældsholderenes risiko stiger, men de får ikke kompensation</li></ul><strong>PE-perspektiv:</strong> Reducerer equity at risk og boosted DPI (Distributions to Paid-In).` },


  /* ══════════════════════════════════════════════
     DECK: PE & BUY-AND-BUILD (pe_bnb)
  ══════════════════════════════════════════════ */

  { deckId:'pe_bnb', q:'Buy-and-Build: Hvad er strategien, og hvorfor dominerer den i Norden?',
    a:`<strong>Buy-and-Build</strong> = køb en solid "platformsvirksomhed" og foretag en række add-on-opkøb for at skabe skala:<br><br><strong>Værdiskabelse via:</strong><ul><li>Multiple arbitrage: Køb add-ons til 6x, sælg samlet platform til 12x</li><li>Geografisk ekspansion</li><li>Produktsortiment-udvidelse</li><li>Stordriftsfordele (shared services)</li></ul><strong>82% af alle nordiske PE-handler i 2025 var add-on-opkøb.</strong><br><br><strong>For Danske Bank:</strong> Én PE-relation kan generere 5–10 fee-mandater over en holdperiode: platform-køb, add-ons, refinansiering, exit.` },

  { deckId:'pe_bnb', q:'Multiple Arbitrage: Hvordan skabes PE-afkast gennem multipler?',
    a:`<strong>Multiple Arbitrage</strong> = forskellen mellem købs- og salgsmultipel:<br><br><strong>Eksempel:</strong><br>• Køb platform til <strong>6x EV/EBITDA</strong> (lille, regional)<br>• Foretag 5 add-ons til <strong>4–5x EV/EBITDA</strong><br>• EBITDA vokser fra 50 til 150 mio. DKK<br>• Sælg samlet platform til <strong>10–12x EV/EBITDA</strong><br>→ EV stiger fra 300 til 1.500–1.800 mio. DKK<br><br><strong>Hvorfor virker det?</strong><ul><li>Større virksomheder handler til højere multipler</li><li>Mere diversificeret = lavere risiko = højere multipel</li><li>Professionaliseret management og systemer</li></ul><strong>2025 median:</strong> 12,9x EV/EBITDA for nordiske PE-exits.` },

  { deckId:'pe_bnb', q:'Axcel: Profil og nyere transaktioner',
    a:`<strong>Axcel</strong> (København/Stockholm) — Nordisk mid-to-large-cap PE:<br><br><strong>Nøgletal:</strong><ul><li><strong>Axcel VII:</strong> EUR 1.296 mio. (lukket feb 2024, +60% vs. forgænger)</li><li><strong>Axcel Elevate:</strong> DKK 2,5 mia. (ny fond)</li><li>68 platformsinvesteringer, 400+ add-ons historisk</li></ul><strong>Nyere handler:</strong><ul><li><strong>DANX Carousel Group:</strong> Pan-europæisk in-night logistics (Fund VI)</li><li><strong>LPR Holding GmbH:</strong> Add-on i Tyskland (jan 2025)</li><li><strong>SuperOffice:</strong> Solgt via continuation vehicle, EUR 266 mio. (jun 2025) — cash EBITDA tredoblet under ejerskab</li></ul>` },

  { deckId:'pe_bnb', q:'EQT: Profil og nyere transaktioner',
    a:`<strong>EQT</strong> — Nordens største PE-hus (Stockholm):<br><br><strong>Nøgletal:</strong><ul><li>Estimeret enterprise value i Norden: <strong>EUR 28,3 mia.</strong></li><li>Aktiv globalt med multiple strategier (PE, Infra, RE, Ventures)</li></ul><strong>Nøgletransaktioner:</strong><ul><li><strong>Karo Healthcare → KKR:</strong> ~EUR 2,5 mia., ~18,9x EV/EBITDA (2025) — masterclass i buy-and-build (8 opkøb, 4x omsætning)</li><li><strong>Fortnox-bud:</strong> USD 4,5 mia. (største nordiske buyout 2025)</li><li><strong>HVD Group + Next:</strong> B2B SaaS til byggebranchen</li></ul>` },

  { deckId:'pe_bnb', q:'Polaris Private Equity: Profil og strategi',
    a:`<strong>Polaris</strong> (København) — Nordisk mid-market PE:<br><br><strong>Fokus:</strong> EUR 20–80 mio. equity-investeringer<br><br><strong>Nyere handler:</strong><ul><li><strong>7N:</strong> Dansk premium IT-konsulent (EUR 210 mio. omsætning, 2024)</li><li><strong>Awardit AB:</strong> Offentligt tilbud SEK 1.143 mio. (Nasdaq First North, marts 2024)</li><li><strong>Salfarm:</strong> Dansk veterinær pharma (dec 2024)</li></ul><strong>B&B track record:</strong><ul><li><strong>ProData:</strong> IT-konsulent, 3 add-ons, solgt til Axcel</li><li><strong>Molslinjen:</strong> Vokset fra 2 til 9 ruter, solgt til EQT Infra</li></ul><strong>Ny fond:</strong> Polaris VI med tilsagn på DKK 6 mia.` },

  { deckId:'pe_bnb', q:'FSN Capital: Profil og InstallatørGruppen som masterclass',
    a:`<strong>FSN Capital</strong> (Oslo/Stockholm/København/München):<br><br><strong>Fonde:</strong><ul><li><strong>FSN Capital VI:</strong> ~EUR 1,85 mia.</li><li><strong>FSN Compass:</strong> EUR 400 mio. (small-cap tematisk, maj 2024)</li><li><strong>FSN Confluence:</strong> EUR 588 mio. (continuation fund, aug 2024)</li></ul><strong>InstallatørGruppen (masterclass):</strong><ul><li>11 danske tekniske installationsvirksomheder samlet dag 1</li><li>DKK 1,3 mia. omsætning fra start</li><li>Add-ons: Optimum Ventilation (DKK 12,1 mio. EBITDA, jun 2024)</li><li>Replikation af Instalco-model (Fund IV → IPO Nasdaq Stockholm 2017)</li></ul>` },

  { deckId:'pe_bnb', q:'PE Fund Economics: Management Fee, Carried Interest og Hurdle Rate',
    a:`<strong>GP (General Partner) Economics:</strong><br><br><strong>Management Fee:</strong> ~2% af committed capital p.a.<br>→ Dækker løn, kontor, operationelle omkostninger<br><br><strong>Carried Interest (Carry):</strong> ~20% af afkastet <em>over</em> hurdle rate<br>→ Den primære incitamentsdriver for GP<br><br><strong>Hurdle Rate:</strong> Typisk 8% p.a. preferred return til LP'er<br>→ GP modtager først carry når LP har fået 8% afkast<br><br><strong>Catch-up:</strong> GP modtager 100% af afkast efter hurdle indtil carry er "inhentet"<br><br><strong>Clawback:</strong> Hvis fonden underperformer i slutningen, skal GP tilbagebetale overskydende carry.` },

  { deckId:'pe_bnb', q:'PE Exit-ruter: Trade Sale vs. Secondary Buyout vs. IPO',
    a:`<strong>Trade Sale (til strategisk køber):</strong><ul><li>Typisk højest pris (synergipræmie 20–40%)</li><li>Cleanest exit (100% salg)</li><li>Risiko: Antitrust, lang regulatory proces</li></ul><strong>Secondary Buyout (til anden PE-fond):</strong><ul><li>Mest efficient eksekvering</li><li>Køber forstår PE-logik (IRR, leverage)</li><li>Lavere pris (ingen synergipræmie)</li></ul><strong>IPO:</strong><ul><li>Kun delvis exit (25–40% solgt ved IPO)</li><li>Kræver stærk equity story og markedsvindue</li><li>Fuld exit via efterfølgende ABB'er over 12–24 mdr.</li></ul><strong>Danske Banks fordel:</strong> Integreret M&A/ECM kan evaluere alle tre simultant (equity-agnostisk).` },

  { deckId:'pe_bnb', q:'53 Overdue PE-Exits i Danmark: Hvad betyder det for deal flow?',
    a:`Der er <strong>53 danske PE-porteføljevirksomheder</strong> med EBITDA >DKK 20 mio. der er "overdue" for exit (holdperiode >5 år), med yderligere 8 der blev overdue i 2025.<br><br><strong>Implikationer:</strong><ul><li>Massiv pipeline af kommende sell-side mandater</li><li>PE-fonde under pres for at returnere kapital til LP'er</li><li>Mange fonde nærmer sig fondenes udløb (typisk 10+2 år)</li></ul><strong>For Danske Bank:</strong> Hvert overdue exit er et potentielt mandat: sell-side M&A, IPO, eller Dual Track.<br><br><em>Deal flow-udsigterne for 2026–2027 er exceptionelt robuste.</em>` },

  { deckId:'pe_bnb', q:'Continuation Vehicles / GP-Led Secondaries: Hvad er det?',
    a:`<strong>Continuation Vehicle</strong> = PE-fond sælger et porteføljeselskab til en ny fond, som GP'en selv styrer:<br><br><strong>Mekanik:</strong><ul><li>Eksisterende LP'er kan vælge at "rulle" (beholde eksponering) eller cashe ud</li><li>Nye LP'er (typisk secondary-fonde som AlpInvest, Lexington) investerer</li><li>GP beholder kontrollen og kan fortsætte værdiskabelse</li></ul><strong>Eksempel:</strong> Axcels SuperOffice solgt via continuation vehicle til EUR 266 mio. med Carlyle AlpInvest som lead investor.<br><br><strong>Hvorfor populært?</strong> PE-fonde der er "overdue" kan returnere kapital til gamle LP'er uden at sælge til den laveste pris.` },


  /* ══════════════════════════════════════════════
     DECK: CASE STUDIES (cases)
  ══════════════════════════════════════════════ */

  { deckId:'cases', q:'Case: EQT → Karo Healthcare → KKR (~EUR 2,5 mia., 2025) — Reverse-engineer denne deal',
    a:`<strong>Strategisk rationale:</strong> EQT transformerede Karo fra nordisk niche til pan-europæisk consumer health-platform via 8 opkøb (E45 fra Reckitt GBP 200 mio., Lamisil fra Haleon GBP 235 mio.).<br><br><strong>Værdiansættelse:</strong> ~EUR 2,5 mia., <strong>~18,9x EV/EBITDA</strong>. Omsætning firedoblet til ~EUR 530–550 mio., EBITDA ~EUR 140 mio.<br><br><strong>Financing (estimat):</strong> 4,5x leverage = ~EUR 630 mio. senior debt. Equity fra KKR: ~EUR 1,87 mia.<br><br><strong>Takeaway:</strong> B&B skaber kvantificerbar værdi. Høj multipel berettiget fordi EBITDA var organisk+addon-drevet, ikke leverage-drevet.` },

  { deckId:'cases', q:'Case: Novo Holdings → Catalent (USD 16,5 mia., 2024) — Strategisk rationale',
    a:`<strong>Kontekst:</strong> Verdens største danske M&A-transaktion nogensinde.<br><br><strong>Rationale:</strong> Novo-økosystemets akutte behov for CDMO-produktionskapacitet til semaglutid (Wegovy/Ozempic).<br><br><strong>Mekanik:</strong><ol><li>Novo Holdings køber hele Catalent for USD 63,50/aktie (47,5% præmie til 60-dages VWAP)</li><li>Tre fill-finish-faciliteter (Anagni, Bruxelles, Bloomington) sælges videre til Novo Nordisk for USD 11,7 mia.</li></ol><strong>Rådgivere:</strong> Goldman Sachs (Novo), Citi + J.P. Morgan (Catalent).<br><br><strong>Takeaway:</strong> Strategisk M&A i life science handler om <em>supply chain-kontrol</em>, ikke traditionelle synergier.` },

  { deckId:'cases', q:'Case: FSN Capital → InstallatørGruppen (DKK 1,3 mia., 2023) — B&B-model',
    a:`<strong>Strategi:</strong> Replikering af Instalco-modellen (Fund IV, 2014 → IPO Nasdaq Stockholm 2017).<br><br><strong>Platform:</strong> 11 danske tekniske installationsvirksomheder samlet simultant:<br>• El, VVS, fiber, ventilation, køling<br>• DKK 1,3 mia. omsætning fra dag 1<br><br><strong>Værdiansættelse (estimat):</strong> 6–9x EV/EBITDA, EBITDA ~DKK 100–130 mio. → EV DKK 600 mio.–1,2 mia.<br><br><strong>Financing:</strong> FSN Capital VI equity + nordiske banker, 3–4x leverage.<br><br><strong>Exit-muligheder:</strong> Trade sale, secondary buyout, eller IPO. Danske Banks integrerede model er ideel til at rådgive på exits af denne type.` },

  { deckId:'cases', q:'Case: Fortum Recycling & Waste → Summa Equity (EUR 800 mio., 2024)',
    a:`<strong>Type:</strong> Carve-out transaktion med Danske Bank som Financial Adviser.<br><br><strong>Sælger:</strong> Fortum (finsk energiselskab) — solgte non-core recycling/affalds-division som led i strategisk fokusering.<br><br><strong>Køber:</strong> Summa Equity — norsk impact-fokuseret PE-fond.<br><br><strong>Værdiansættelse:</strong> EUR 800 mio. EV. Typiske multiples for recycling/waste: 8–12x EV/EBITDA.<br><br><strong>Takeaway:</strong> Carve-outs er en central del af sell-side M&A. Danske Banks Finland-franchise ("ledende M&A/ECM-rådgiver i Finland") genererer mandater som dette.` },

  { deckId:'cases', q:'Case: Cargotec/Kalmar Demerger + Notering (EUR 1,6 mia., 2024)',
    a:`<strong>Type:</strong> Corporate restructuring + ECM — illustrerer integreret M&A/ECM-model.<br><br><strong>Rådgivere:</strong> Danske Bank + Goldman Sachs + BNP Paribas.<br><br><strong>Mekanik:</strong><ul><li>Cargotec demerger'ede Kalmar som selvstændigt selskab</li><li>Kalmar noteret på Nasdaq Helsinki</li><li>Transaktion til EUR 1,6 mia.</li></ul><strong>Kompleksitet:</strong> Krævede simultant M&A-struktureringsarbejde (demerger-mekanik, separation af aktiver) og ECM-eksekvering (notering, investor outreach).<br><br><strong>Takeaway:</strong> Demerger + listing er en transaction type der <em>kun</em> kan håndteres effektivt af et integreret M&A/ECM-team.` },

  { deckId:'cases', q:'Reverse Engineering-metode: Hvordan dekonstruerer du en transaktion?',
    a:`<strong>Systematisk 4-trins metode:</strong><br><br><strong>Trin 1 — Identificer og saml data:</strong><br>MergerMarket, Capital IQ, Bloomberg, selskabsmeddelelser, pressemeddelelser.<br><br><strong>Trin 2 — Fastlæg værdiansættelse:</strong><br>Beregn EV/EBITDA, EV/Revenue, P/E. Sammenlign med peers og precedents.<br><br><strong>Trin 3 — Rekonstruer financing:</strong><br>Estimer leverage (4–5x EBITDA), equity-bidrag (30–50%), finansieringskilder.<br><br><strong>Trin 4 — Forstå strategisk rationale:</strong><br>Hvorfor denne pris? Synergipotentiale? Buy-and-build plan? Markedspositionering?<br><br><em>Denne muskel skal trænes — øv dig på minimum 5 Danske Bank-transaktioner.</em>` },

  { deckId:'cases', q:'Roche/Zealand Pharma (op til USD 5,3 mia., 2025) — Hvad fortæller denne deal?',
    a:`<strong>Type:</strong> Single-asset partnerskabsaftale — den største i obesity-feltet nogensinde.<br><br><strong>Detaljer:</strong><ul><li>Roches licens til petrelintid (amylin-analog til fedme) fra Zealand Pharma</li><li>USD 1,65 mia. upfront + op til USD 5,3 mia. med milestones</li></ul><strong>Kontekst:</strong> Bekræfter Danmarks position som <em>globalt epicenter</em> for life science M&A.<br><br><strong>Relaterede deals:</strong><ul><li>AbbVie/Gubra (op til USD 2,2 mia., 2025)</li><li>Genmab/Merus (~USD 8 mia., 2025)</li></ul><strong>Takeaway:</strong> Novo-økosystemet genererede alene >USD 30 mia. i M&A-værdi i 2024–2025.` },


  /* ══════════════════════════════════════════════
     DECK: ANALYST TOOLKIT (toolkit)
  ══════════════════════════════════════════════ */

  { deckId:'toolkit', q:'Excel uden mus: De 15 vigtigste genveje for IB-analytikere',
    a:`<table style="width:100%;font-size:12px"><tr><td><code>Ctrl+Shift+L</code></td><td>Toggle filter</td></tr><tr><td><code>Alt+E+S+V</code></td><td>Paste values</td></tr><tr><td><code>Ctrl+PgUp/Dn</code></td><td>Skift ark</td></tr><tr><td><code>F4</code></td><td>Toggle absolute ref / gentag handling</td></tr><tr><td><code>Ctrl+[</code></td><td>Trace precedents (gå til kilde)</td></tr><tr><td><code>Alt+;</code></td><td>Select visible cells only</td></tr><tr><td><code>Ctrl+Shift+End</code></td><td>Select til sidste celle</td></tr><tr><td><code>Ctrl+1</code></td><td>Format cells</td></tr><tr><td><code>Ctrl+Shift+~</code></td><td>Vis formler</td></tr><tr><td><code>Alt+Enter</code></td><td>Linjeskift i celle</td></tr><tr><td><code>Ctrl+D</code></td><td>Fyld ned</td></tr><tr><td><code>Ctrl+Space</code></td><td>Vælg kolonne</td></tr><tr><td><code>Shift+Space</code></td><td>Vælg række</td></tr><tr><td><code>Ctrl+Shift+1</code></td><td>Tal-format med tusindtal</td></tr><tr><td><code>F2</code></td><td>Redigér celle</td></tr></table><br><strong>Regel:</strong> Brug <em>aldrig</em> musen i en model. Det er langsomt og signalerer umodenhed.` },

  { deckId:'toolkit', q:'BLUF / Pyramid Principle: Hvordan kommunikerer du opad?',
    a:`<strong>BLUF (Bottom Line Up Front)</strong> / Pyramid Principle:<br><br><strong>Format:</strong><ol><li><strong>Svaret først:</strong> Konklusion/anbefaling i første sætning</li><li><strong>Understøttende data:</strong> 2–3 kvantitative datapunkter</li><li><strong>Baggrund:</strong> Udelad metode medmindre der specifikt spørges</li></ol><strong>Eksempel:</strong><br><em>"Project Odin: Revideret LBO-model viser 18,2% IRR i base case (ned fra 19,4%) efter opdateret capex-antagelse. Attached v14. Key delta: maintenance capex øget med DKK 15m p.a. baseret på mgmt feedback. Klar til review."</em><br><br><strong>Aldrig:</strong> "Hope you're well", indledninger, eller procesbeskrivelser.` },

  { deckId:'toolkit', q:'Red Pen Proofing: Kvalitetskontrol-proces for IB-dokumenter',
    a:`<strong>Før ethvert dokument forlader dit skrivebord:</strong><br><br><ol><li><strong>Print det ud.</strong> Øjet fanger fejl på papir som det overser på skærm</li><li><strong>Rød kuglepen + lineal:</strong> "Tie-outs" — verificér at totaler stemmer</li></ol><strong>Check specifikt:</strong><ul><li>✗ Tal der ikke summerer</li><li>✗ Inkonsekvens i enheder (mio./mia.)</li><li>✗ Stavefejl i virksomheds- og personnavne</li><li>✗ Formateringsinkonsekvens (font, størrelse, decimaler)</li><li>✗ Sidehoveder med korrekt dato og "CONFIDENTIAL"</li></ul><br><strong>Regel:</strong> <em>"Én formateringsfejl underminerer hele dokumentets troværdighed."</em>` },

  { deckId:'toolkit', q:'Versionskontrol: Filnavngivning og discipline i IB',
    a:`<strong>Standard filnavngivning:</strong><br><code>[Projekt]_[Type]_[Version]_[Dato]_[Initialer]</code><br><br><strong>Eksempel:</strong><br><code>ProjectOdin_LBOModel_v14_20260815_JK</code><br><br><strong>Regler:</strong><ul><li><strong>Gem aldrig over en eksisterende fil</strong> — altid ny version</li><li>Brug SharePoint som supplement, stol aldrig udelukkende på den</li><li>Hold styr på "latest version" via en simpel log</li></ul><strong>Worst case:</strong> En MD åbner den forkerte version klokken 07:00 og præsenterer forældede tal. <em>Det er din fejl.</em><br><br><strong>Open Loops:</strong> Før komplet liste over alle åbne opgaver. Gennemgå 3x dagligt (morgen, efter frokost, før du går).` },

  { deckId:'toolkit', q:'Capital IQ, FactSet, Bloomberg: De tre terminaler og deres styrker',
    a:`<strong>Capital IQ (S&P):</strong><ul><li>Comps-data, precedent transactions, virksomhedsoplysninger</li><li>Screening-funktion til peer universer</li><li>Excel-formler: <code>=CIQ(...)</code></li></ul><strong>FactSet:</strong><ul><li>Stærkere på earnings estimates og consensus</li><li>God til nordiske mid-caps med begrænset CIQ-dækning</li><li>Excel: <code>=FDS(...)</code></li></ul><strong>Bloomberg Terminal:</strong><ul><li>Real-time markedsdata, renter, credit spreads, news</li><li>Nøglekommandoer: <code>COMP</code>, <code>FA</code>, <code>MA</code>, <code>NI</code>, <code>SRCH</code></li><li>Excel: <code>=BDP(...)</code>, <code>=BDH(...)</code></li></ul>` },

  { deckId:'toolkit', q:'Model Best Practices: Hardcodes, formler og struktur',
    a:`<strong>Farvekodning (standard):</strong><ul><li><span style="color:#0066CC">Blå skrift</span> = hardcoded input / antagelse</li><li>Sort skrift = formel / beregning</li><li><span style="color:#006600">Grøn skrift</span> = link til andet ark</li></ul><strong>Regler:</strong><ul><li><strong>Aldrig</strong> hardcodes inde i en formel</li><li>INDEX/MATCH frem for skrøbelige cellereferencer</li><li>Én antagelse = én celle (reference derfra)</li><li>Separate ark: Inputs → Calculations → Outputs</li></ul><strong>Cirkulære referencer:</strong><br>Typisk årsag: Renter påvirker cash sweep → gældsniveau → renter.<br>Løsning: Iterative calculations eller copy-paste macro.` },

  { deckId:'toolkit', q:'Staffing: Pool → Request → Self-Sourced — Hvordan avancerer du?',
    a:`<strong>Tre arketyper:</strong><br><br><strong>1. Pool-staffing (Mdr. 0–6):</strong><br>Standard for nye analysts. Allokeres baseret på tilgængelighed. Begrænset indflydelse på mandater.<br><br><strong>2. Request-staffing (Mdr. 6+):</strong><br>Senior bankere anmoder specifikt om dig. <em>Dette er målet.</em> Bedre deals, mere ansvar, stærkere mentorrelationer.<br><br><strong>3. Self-sourced (Sjældent for analysts):</strong><br>Du bidrager selv til deal origination via sektorkompetence.<br><br><strong>Vejen:</strong><br>Dag 1–30: Levér fejlfrit, til tiden<br>Dag 30–60: Levér mere end der bedes om<br>Dag 60–90: Bliv uundværlig på ét deal` },

  { deckId:'toolkit', q:'Deal Sheet: Hvad er det og hvordan bygger du det?',
    a:`<strong>Deal Sheet</strong> = dit interne og eksterne CV over transaktioner:<br><br><strong>Format (A4):</strong><ul><li>Klientnavn</li><li>Transaktionstype (sell-side M&A, buy-side, ECM, fairness opinion)</li><li>Enterprise Value</li><li>Din specifikke rolle (modellering, VDR, buyer outreach, prospekt)</li><li>Outcome / status</li></ul><strong>Regler:</strong><ul><li>Dokumentér <strong>hver eneste transaktion</strong> du rører</li><li>Opdatér ugentligt</li><li>Specificér præcist dit bidrag (ikke bare "worked on")</li></ul><strong>Eksempel:</strong> "Ansvarlig for bygning af fuldt integreret LBO-model med multiple kapitalstrukturer" eller "Styrede VDR-infrastruktur for 12 bydere."` },

  { deckId:'toolkit', q:'De første 90 dages handlingsplan for en ny IB-analyst',
    a:`<strong>Dag 1–7:</strong><ul><li>Opsæt arbejdsstation (CIQ, FactSet, Bloomberg plug-ins)</li><li>Download Danske Banks standard templates</li><li>Lær filstruktur og SharePoint</li><li>Spørg staffer: "Hvad er de 3 vigtigste aktive deals?"</li></ul><strong>Dag 8–21:</strong><ul><li>Lever første opgaver hurtigere og bedre end forventet</li><li>Læs Nasdaq Copenhagen meddelelser dagligt</li><li>Abonner på MergerMarket Nordic alerts</li></ul><strong>Dag 22–45:</strong><ul><li>Staffet på 1–2 aktive deals — forstå dem i dybden</li><li>Byg personlige templates (LBO, DCF, comps, tracker)</li></ul><strong>Dag 46–90:</strong><ul><li>Min. 2–3 mandater på deal sheet</li><li>Demonstrér deadline-pres uden kvalitetsfald</li></ul>` },

  { deckId:'toolkit', q:'Circular References i LBO-modeller: Hvad forårsager dem og hvordan fixes de?',
    a:`<strong>Typisk årsag:</strong><br>Renteudgifter → påvirker cash flow → påvirker cash sweep → påvirker gældsniveau → påvirker renteudgifter → ∞<br><br><strong>Fejlfindingsproces:</strong><ol><li>Deaktivér automatiske beregninger</li><li>Brug "Trace Precedents/Dependents" for at isolere cirklen</li><li>Identificér præcis hvor cirklen opstod (typisk efter RCF-ændring)</li></ol><strong>Løsninger:</strong><ul><li><strong>Iterative calculations:</strong> Excel → Options → Formulas → Enable iterative (max 100 iterations)</li><li><strong>Copy-paste macro:</strong> Bryder cirklen mekanisk</li><li><strong>Plug-variabel:</strong> Brug forrige periods rente som estimat</li></ul><strong>Vigtigst:</strong> Hav altid en fungerende "v-1" du kan falde tilbage på.` },

  { deckId:'toolkit', q:'"Go-To Analyst"-profilen: Hvad adskiller de bedste under pres?',
    a:`<strong>Scenarie:</strong> Fredag kl. 19:00. Modellen crasher. Klienten har board-møde mandag 08:00.<br><br><strong>Go-To Analyst respons:</strong> "Ja. Send seneste version. Jeg ringer inden 23:00 med status."<br><br><strong>Nøglekarakteristika:</strong><ul><li><strong>Ingen panik.</strong> Rolig under pres er en trænet færdighed</li><li><strong>Systematisk fejlfinding:</strong> Forstå hvad der er galt FØR du retter</li><li><strong>Kommunikation opad:</strong> Proaktive statusopdateringer. 3 timers stilhed = VP antager det værste</li><li><strong>Kvalitet > hastighed.</strong> Hurtig model med fejl er værre end 2 timer forsinket men korrekt</li><li><strong>"Jeg ved det ikke, men jeg finder ud af det inden 30 min."</strong> Uvidenhed er ok. At skjule det er ikke.</li></ul>` },

];
